build-wsl-release:
	# command to build the release as a package. 
	pyinstaller.exe --noconsole populateDB-gui-qt.py --onefile --name Slippi-DB-Populate

build-linux-release:
	pyinstaller --noconsole populateDB-gui-qt.py --onefile --name Slippi-DB-Populate